defmodule Repro.Repo.Migrations.Initial do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:comments, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:body, :text)
      add(:post_id, :uuid)
    end

    create table(:posts, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:comments) do
      modify(
        :post_id,
        references(:posts,
          column: :id,
          name: "comments_post_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:posts) do
      add(:title, :text)
      add(:score, :bigint)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end
  end

  def down do
    alter table(:posts) do
      remove(:inserted_at)
      remove(:score)
      remove(:title)
    end

    drop(constraint(:comments, "comments_post_id_fkey"))

    alter table(:comments) do
      modify(:post_id, :uuid)
    end

    drop(table(:posts))

    drop(table(:comments))
  end
end
